In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"] = (20,10)

In [3]:
file_path = "E:/7th semester/Deep Learning/labs/DL-Assigment/data/stock_data.csv"
data = pd.read_csv(file_path)
data

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week,52_Week_Low,Sector
0,6/1/2025,AAPL,185.96,187.79,188.85,183.74,42257183,2.931360e+12,28.37,0.49,6.62,248.20,155.68,Technology
1,6/1/2025,ABBV,189.63,193.64,194.31,188.03,33074970,3.289230e+11,16.74,3.51,11.57,210.83,127.91,Healthcare
2,6/1/2025,ABT,118.79,120.08,120.53,118.01,17130934,2.001330e+11,19.39,1.84,6.19,140.79,99.26,Healthcare
3,6/1/2025,ADBE,584.51,567.78,587.97,561.25,11080360,2.460380e+11,43.29,0.00,13.12,727.11,407.82,Technology
4,6/1/2025,ADP,253.46,255.60,258.59,249.91,10319559,1.052470e+11,29.92,2.04,8.54,303.75,234.28,Financials
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4341,7/23/2025,VRTX,478.20,489.78,491.84,476.65,7141573,1.275470e+11,28.64,0.00,17.10,603.57,411.70,Healthcare
4342,7/23/2025,VZ,46.61,47.75,48.26,46.15,9865947,1.856940e+11,9.31,5.82,5.13,53.28,40.22,Communication Services
4343,7/23/2025,WMT,71.65,70.99,72.35,70.46,22059711,5.560060e+11,25.93,1.27,2.74,90.05,62.53,Consumer Staples
4344,7/23/2025,XOM,117.02,112.37,118.45,111.41,13557718,4.403070e+11,15.72,3.09,7.15,122.66,100.50,Energy
4345,7/23/2025,ZTS,146.81,148.32,150.25,145.16,5102989,6.723840e+10,29.39,0.74,5.05,184.27,110.21,Healthcare

In [4]:
data.groupby('Ticker')['Ticker'].agg('count')

Ticker
AAPL    53
ABBV    53
ABT     53
ADBE    53
ADP     53
        ..
VRTX    53
VZ      53
WMT     53
XOM     53
ZTS     53
Name: Ticker, Length: 82, dtype: int64

In [7]:
## remove the irrelavant data columns in dataset

In [6]:
data_new = data.drop(['52_Week_Low', 'Sector'], axis='columns')
data_new.head()

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week
0,6/1/2025,AAPL,185.96,187.79,188.85,183.74,42257183,2.931360e+12,28.37,0.49,6.62,248.20
1,6/1/2025,ABBV,189.63,193.64,194.31,188.03,33074970,3.289230e+11,16.74,3.51,11.57,210.83
2,6/1/2025,ABT,118.79,120.08,120.53,118.01,17130934,2.001330e+11,19.39,1.84,6.19,140.79
3,6/1/2025,ADBE,584.51,567.78,587.97,561.25,11080360,2.460380e+11,43.29,0.00,13.12,727.11
4,6/1/2025,ADP,253.46,255.60,258.59,249.91,10319559,1.052470e+11,29.92,2.04,8.54,303.75

In [9]:
print(data_new.columns.tolist())

['Date', 'Ticker', 'Open Price', 'Close Price', 'High Price', 'Low Price', 'Volume Traded', 'Market Cap', 'PE Ratio', 'Dividend Yield', 'EPS', '52 Week ']

In [ ]:
## checking waht are the null values of dataset

In [12]:
data = data_new.isnull().sum()
data

Date              0
Ticker            0
Open Price        0
Close Price       0
High Price        0
Low Price         0
Volume Traded     0
Market Cap        0
PE Ratio          0
Dividend Yield    0
EPS               0
52 Week           0
dtype: int64

In [ ]:
## filter only AAPL compony related data from the dataset

In [18]:
data_AAPL = data_new[data_new['Ticker']=='AAPL'].copy()
data_AAPL

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week
0,6/1/2025,AAPL,185.96,187.79,188.85,183.74,42257183,2.931360e+12,28.37,0.49,6.62,248.20
82,6/2/2025,AAPL,211.57,213.07,214.91,210.10,49806398,3.325970e+12,25.98,0.51,8.20,258.68
164,6/3/2025,AAPL,197.75,195.61,200.13,193.48,29588431,3.053420e+12,30.35,0.52,6.45,233.17
246,6/4/2025,AAPL,215.31,215.44,217.79,214.77,38591730,3.362970e+12,25.26,0.47,8.53,288.47
328,6/5/2025,AAPL,218.80,226.08,228.69,216.68,73159323,3.529050e+12,30.97,0.46,7.30,284.50
410,6/6/2025,AAPL,200.95,195.53,203.35,192.85,64831615,3.052180e+12,27.23,0.47,7.18,259.72
492,6/7/2025,AAPL,216.21,210.88,219.20,210.03,83351924,3.291790e+12,28.18,0.54,7.48,238.83
574,6/8/2025,AAPL,207.88,213.54,215.04,206.62,39916529,3.333310e+12,24.67,0.53,8.66,257.50
656,6/9/2025,AAPL,219.80,212.32,220.42,211.70,80271583,3.314260e+12,31.12,0.52,6.82,275.76
738,6/10/2025,AAPL,194.39,189.83,195.30,187.27,57886165,2.963200e+12,30.07,0.55,6.31,243.80
820,6/11/2025,AAPL,208.96,207.24,211.88,204.17,53460564,3.234970e+12,28.33,0.50,7.32,253.37
902,6/12/2025,AAPL,207.38,202.29,208.91,200.11,78890213,3.157700e+12,31.70,0.54,6.38,245.10
984,6/13/2025,AAPL,216.46,223.10,225.00,214.46,32700906,3.482540e+12,26.14,0.49,8.53,242.97
1066,6/14/2025,AAPL,201.33,196.73,203.98,196.20,39688810,3.070910e+12,30.52,0.51,6.45,263.07
1148,6/15/2025,AAPL,199.00,196.46,201.77,195.75,46150506,3.066690e+12,25.54,0.50,7.69,261.11
1230,6/16/2025,AAPL,222.41,222.29,223.84,219.38,78806115,3.469890e+12,31.18,0.52,7.13,289.24
1312,6/17/2025,AAPL,210.81,216.04,218.69,208.38,72291823,3.372330e+12,30.61,0.53,7.06,244.70
1394,6/18/2025,AAPL,194.59,188.00,196.59,187.27,47539394,2.934630e+12,25.80,0.51,7.29,246.60
1476,6/19/2025,AAPL,199.36,195.78,201.80,193.75,44235706,3.056080e+12,30.53,0.47,6.41,219.27
1558,6/20/2025,AAPL,196.85,194.79,197.57,193.40,89963019,3.040620e+12,29.97,0.48,6.50,245.43
1640,6/21/2025,AAPL,192.89,198.86,199.64,192.46,73748396,3.104160e+12,29.02,0.49,6.85,231.86
1722,6/22/2025,AAPL,201.28,203.90,206.80,199.27,54158886,3.182830e+12,29.40,0.47,6.94,249.01
1804,6/23/2025,AAPL,202.61,197.39,205.36,196.75,73747012,3.081210e+12,31.73,0.51,6.22,213.97
1886,6/24/2025,AAPL,222.51,222.00,223.04,220.04,33191275,3.465370e+12,30.21,0.45,7.35,277.06
1968,6/25/2025,AAPL,215.22,221.52,222.95,214.04,83276813,3.457870e+12,25.42,0.53,8.71,271.24
2050,6/26/2025,AAPL,194.12,194.77,195.19,192.73,40298042,3.040310e+12,29.29,0.50,6.65,217.35
2132,6/27/2025,AAPL,208.27,211.97,212.83,207.80,66348207,3.308800e+12,29.56,0.48,7.17,267.10
2214,6/28/2025,AAPL,198.75,199.02,202.00,196.56,57652618,3.106650e+12,25.31,0.46,7.86,228.42
2296,6/29/2025,AAPL,206.84,201.11,209.51,199.79,71165046,3.139280e+12,25.27,0.54,7.96,251.36
2378,6/30/2025,AAPL,215.49,219.40,221.34,215.02,45998441,3.424780e+12,30.95,0.47,7.09,242.10
2460,7/1/2025,AAPL,192.81,190.24,195.43,189.80,27168122,2.969600e+12,24.52,0.55,7.76,226.15
2542,7/2/2025,AAPL,187.60,183.06,188.28,182.01,51381325,2.857520e+12,30.92,0.48,5.92,220.03
2624,7/3/2025,AAPL,222.89,218.45,225.99,216.62,60679141,3.409950e+12,30.80,0.50,7.09,282.44
2706,7/4/2025,AAPL,210.70,208.19,213.58,205.31,86591918,3.249800e+12,32.17,0.50,6.47,251.31
2788,7/5/2025,AAPL,209.67,215.02,217.58,207.13,82657325,3.356410e+12,28.26,0.48,7.61,238.09
2870,7/6/2025,AAPL,212.31,205.81,213.58,204.36,88301007,3.212640e+12,27.65,0.48,7.44,248.20
2952,7/7/2025,AAPL,209.63,206.29,212.66,204.88,43060292,3.220140e+12,30.65,0.50,6.73,230.06
3034,7/8/2025,AAPL,221.26,215.43,223.21,213.52,46402305,3.362810e+12,27.94,0.49,7.71,241.15
3116,7/9/2025,AAPL,213.75,216.17,218.81,212.37,48567317,3.374360e+12,24.51,0.53,8.82,233.60
3198,7/10/2025,AAPL,194.80,192.13,195.41,189.64,54107283,2.999100e+12,26.17,0.49,7.34,252.67
3280,7/11/2025,AAPL,205.83,204.83,206.94,204.01,57265744,3.197350e+12,25.88,0.51,7.91,246.84
3362,7/12/2025,AAPL,210.05,203.44,211.10,202.10,86274927,3.175650e+12,24.42,0.47,8.33,242.05
3444,7/13/2025,AAPL,219.17,218.61,222.24,217.90,61391617,3.412450e+12,28.73,0.47,7.61,246.82
3526,7/14/2025,AAPL,189.06,186.16,189.76,184.44,58230115,2.905910e+12,27.31,0.52,6.82,214.22
3608,7/15/2025,AAPL,222.18,222.00,223.75,219.76,72685329,3.465370e+12,27.62,0.53,8.04,242.33
3690,7/16/2025,AAPL,216.50,221.57,224.88,214.25,78138322,3.458650e+12,29.66,0.53,7.47,296.99
3772,7/17/2025,AAPL,204.39,207.31,210.06,202.83,60986182,3.236060e+12,30.84,0.46,6.72,237.23
3854,7/18/2025,AAPL,199.18,201.64,204.61,196.28,88722987,3.147550e+12,27.52,0.51,7.33,255.28
3936,7/19/2025,AAPL,224.82,228.20,229.43,221.75,88333192,3.562150e+12,30.49,0.50,7.48,272.17
4018,7/20/2025,AAPL,223.42,229.93,230.88,221.29,48637707,3.589150e+12,24.25,0.47,9.48,294.12
4100,7/21/2025,AAPL,200.09,196.05,202.05,194.61,67974129,3.060290e+12,25.20,0.52,7.78,257.18
4182,7/22/2025,AAPL,196.40,200.44,201.53,194.10,88201942,3.128820e+12,28.49,0.52,7.04,253.29
4264,7/23/2025,AAPL,200.71,198.96,201.89,197.48,39506796,3.105720e+12,29.86,0.49,6.66,251.26

In [19]:
## reset the index numbers

In [21]:
data_AAPL.reset_index(drop=True, inplace=True)
data_AAPL

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week
0,6/1/2025,AAPL,185.96,187.79,188.85,183.74,42257183,2.931360e+12,28.37,0.49,6.62,248.20
1,6/2/2025,AAPL,211.57,213.07,214.91,210.10,49806398,3.325970e+12,25.98,0.51,8.20,258.68
2,6/3/2025,AAPL,197.75,195.61,200.13,193.48,29588431,3.053420e+12,30.35,0.52,6.45,233.17
3,6/4/2025,AAPL,215.31,215.44,217.79,214.77,38591730,3.362970e+12,25.26,0.47,8.53,288.47
4,6/5/2025,AAPL,218.80,226.08,228.69,216.68,73159323,3.529050e+12,30.97,0.46,7.30,284.50
5,6/6/2025,AAPL,200.95,195.53,203.35,192.85,64831615,3.052180e+12,27.23,0.47,7.18,259.72
6,6/7/2025,AAPL,216.21,210.88,219.20,210.03,83351924,3.291790e+12,28.18,0.54,7.48,238.83
7,6/8/2025,AAPL,207.88,213.54,215.04,206.62,39916529,3.333310e+12,24.67,0.53,8.66,257.50
8,6/9/2025,AAPL,219.80,212.32,220.42,211.70,80271583,3.314260e+12,31.12,0.52,6.82,275.76
9,6/10/2025,AAPL,194.39,189.83,195.30,187.27,57886165,2.963200e+12,30.07,0.55,6.31,243.80
10,6/11/2025,AAPL,208.96,207.24,211.88,204.17,53460564,3.234970e+12,28.33,0.50,7.32,253.37
11,6/12/2025,AAPL,207.38,202.29,208.91,200.11,78890213,3.157700e+12,31.70,0.54,6.38,245.10
12,6/13/2025,AAPL,216.46,223.10,225.00,214.46,32700906,3.482540e+12,26.14,0.49,8.53,242.97
13,6/14/2025,AAPL,201.33,196.73,203.98,196.20,39688810,3.070910e+12,30.52,0.51,6.45,263.07
14,6/15/2025,AAPL,199.00,196.46,201.77,195.75,46150506,3.066690e+12,25.54,0.50,7.69,261.11
15,6/16/2025,AAPL,222.41,222.29,223.84,219.38,78806115,3.469890e+12,31.18,0.52,7.13,289.24
16,6/17/2025,AAPL,210.81,216.04,218.69,208.38,72291823,3.372330e+12,30.61,0.53,7.06,244.70
17,6/18/2025,AAPL,194.59,188.00,196.59,187.27,47539394,2.934630e+12,25.80,0.51,7.29,246.60
18,6/19/2025,AAPL,199.36,195.78,201.80,193.75,44235706,3.056080e+12,30.53,0.47,6.41,219.27
19,6/20/2025,AAPL,196.85,194.79,197.57,193.40,89963019,3.040620e+12,29.97,0.48,6.50,245.43
20,6/21/2025,AAPL,192.89,198.86,199.64,192.46,73748396,3.104160e+12,29.02,0.49,6.85,231.86
21,6/22/2025,AAPL,201.28,203.90,206.80,199.27,54158886,3.182830e+12,29.40,0.47,6.94,249.01
22,6/23/2025,AAPL,202.61,197.39,205.36,196.75,73747012,3.081210e+12,31.73,0.51,6.22,213.97
23,6/24/2025,AAPL,222.51,222.00,223.04,220.04,33191275,3.465370e+12,30.21,0.45,7.35,277.06
24,6/25/2025,AAPL,215.22,221.52,222.95,214.04,83276813,3.457870e+12,25.42,0.53,8.71,271.24
25,6/26/2025,AAPL,194.12,194.77,195.19,192.73,40298042,3.040310e+12,29.29,0.50,6.65,217.35
26,6/27/2025,AAPL,208.27,211.97,212.83,207.80,66348207,3.308800e+12,29.56,0.48,7.17,267.10
27,6/28/2025,AAPL,198.75,199.02,202.00,196.56,57652618,3.106650e+12,25.31,0.46,7.86,228.42
28,6/29/2025,AAPL,206.84,201.11,209.51,199.79,71165046,3.139280e+12,25.27,0.54,7.96,251.36
29,6/30/2025,AAPL,215.49,219.40,221.34,215.02,45998441,3.424780e+12,30.95,0.47,7.09,242.10
30,7/1/2025,AAPL,192.81,190.24,195.43,189.80,27168122,2.969600e+12,24.52,0.55,7.76,226.15
31,7/2/2025,AAPL,187.60,183.06,188.28,182.01,51381325,2.857520e+12,30.92,0.48,5.92,220.03
32,7/3/2025,AAPL,222.89,218.45,225.99,216.62,60679141,3.409950e+12,30.80,0.50,7.09,282.44
33,7/4/2025,AAPL,210.70,208.19,213.58,205.31,86591918,3.249800e+12,32.17,0.50,6.47,251.31
34,7/5/2025,AAPL,209.67,215.02,217.58,207.13,82657325,3.356410e+12,28.26,0.48,7.61,238.09
35,7/6/2025,AAPL,212.31,205.81,213.58,204.36,88301007,3.212640e+12,27.65,0.48,7.44,248.20
36,7/7/2025,AAPL,209.63,206.29,212.66,204.88,43060292,3.220140e+12,30.65,0.50,6.73,230.06
37,7/8/2025,AAPL,221.26,215.43,223.21,213.52,46402305,3.362810e+12,27.94,0.49,7.71,241.15
38,7/9/2025,AAPL,213.75,216.17,218.81,212.37,48567317,3.374360e+12,24.51,0.53,8.82,233.60
39,7/10/2025,AAPL,194.80,192.13,195.41,189.64,54107283,2.999100e+12,26.17,0.49,7.34,252.67
40,7/11/2025,AAPL,205.83,204.83,206.94,204.01,57265744,3.197350e+12,25.88,0.51,7.91,246.84
41,7/12/2025,AAPL,210.05,203.44,211.10,202.10,86274927,3.175650e+12,24.42,0.47,8.33,242.05
42,7/13/2025,AAPL,219.17,218.61,222.24,217.90,61391617,3.412450e+12,28.73,0.47,7.61,246.82
43,7/14/2025,AAPL,189.06,186.16,189.76,184.44,58230115,2.905910e+12,27.31,0.52,6.82,214.22
44,7/15/2025,AAPL,222.18,222.00,223.75,219.76,72685329,3.465370e+12,27.62,0.53,8.04,242.33
45,7/16/2025,AAPL,216.50,221.57,224.88,214.25,78138322,3.458650e+12,29.66,0.53,7.47,296.99
46,7/17/2025,AAPL,204.39,207.31,210.06,202.83,60986182,3.236060e+12,30.84,0.46,6.72,237.23
47,7/18/2025,AAPL,199.18,201.64,204.61,196.28,88722987,3.147550e+12,27.52,0.51,7.33,255.28
48,7/19/2025,AAPL,224.82,228.20,229.43,221.75,88333192,3.562150e+12,30.49,0.50,7.48,272.17
49,7/20/2025,AAPL,223.42,229.93,230.88,221.29,48637707,3.589150e+12,24.25,0.47,9.48,294.12
50,7/21/2025,AAPL,200.09,196.05,202.05,194.61,67974129,3.060290e+12,25.20,0.52,7.78,257.18
51,7/22/2025,AAPL,196.40,200.44,201.53,194.10,88201942,3.128820e+12,28.49,0.52,7.04,253.29
52,7/23/2025,AAPL,200.71,198.96,201.89,197.48,39506796,3.105720e+12,29.86,0.49,6.66,251.26